### ISSUE TITLE
12章之后就没有了

### ISSUE THREAD

**Issue by zaoying** [chai2010/go-ast-book#22]
就好像看小说到最精彩的部分，突然没了

**Comment by snowcrumble** [comment]
保密 +1

**Comment by YZerui** [comment]
在研究go编译相关的知识，有幸拜读此系列著作，这是目前网上讲的目前看最全面系统的了，但发现在SSA这块停止了更新，希望能发一份完整的到我这边myzerui@163.com，保证不外传+1.

**Comment by CengSin** [comment]
这本书还没出版吗？看到11章之后就发现404了，想买一本结果没找到。希望作者能给我发一份PDF，感谢。

**Comment by brewlin** [comment]
感谢作者写的文章特别好，目前也是看到缺少了ssa、llvm方面的章节，特别希望阅读下作者对于ssa 和llvm方面的见解，希望作者也能发我一份资料，邮箱:97404667@qq.com 保证不外传

**Comment by chennqqi** [comment]
@chai2010 chennqqi@qq.com 能否也给我发一份。另外您的书出版了吗，购买链接也发一下。另外建议挂个github sponsor链接，让大家一起支持作者

**Comment by weixuan19930** [comment]
感谢作者的分享，看到一半中断了，求一份369608497@qq.com

**Comment by verymiao** [comment]
您好，已关注您 github，项目已 star, 希望发一份 pdf 版本个人观看 23237683@qq.com

**Comment by AdwindOne** [comment]
> 已发邮箱，注意查收

能发我一份吗 作者 535319719@qq.com 研究学习，你纸质书出版也会买的
